services:
  web:
    build: .
    command: gunicorn --config gunicorn_config.py ecommerce.wsgi:application
    volumes:
      - .:/app
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - default

  redis:
    image: redis:latest
    expose:
      - 6379
    networks:
      - default

networks:
  default:
    driver: bridge
