services:
  web:
    build: .
    command: gunicorn --config gunicorn_config.py ecommerce.wsgi:application
    volumes:
      - .:/app

    expose:
      - 8000
    env_file:
      - .env

  nginx:
    image: nginx:latest

    ports:
      - 8000:80

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - web
