# Generated by Django 5.0.7 on 2024-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('delivery', models.TextField()),
                ('theBest', models.TextField()),
                ('firstDelivery', models.TextField()),
                ('firstDelivery2', models.TextField()),
                ('saveUp', models.FloatField()),
            ],
        ),
    ]
