# Generated by Django 5.0.7 on 2024-08-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0002_faq_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='firstDelivery',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='firstDelivery2',
            field=models.TextField(blank=True),
        ),
    ]
