# Generated by Django 5.0.7 on 2024-08-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0003_alter_subscription_firstdelivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='delivery',
            field=models.TextField(default='Free Delivery'),
        ),
    ]
